### ISSUE TITLE
cfg-lock

### ISSUE THREAD

**Issue by petejkim** [samuel21119/Intel-i9-10900-Gigabyte-Z490-Vision-G-Hackintosh#1]
Have you tried the cfg-lock fix detailed in [this post](https://www.tonymacx86.com/threads/gigabyte-z490-vision-d-thunderbolt-3-i5-10400-amd-rx-580.298642/)? It is for the Gigabyte Vision D, but I thought it might work on a VIsion G as well.

**Comment by samuel21119** [comment]
Thanks for the information! I successfully disabled CFG-Lock using CFGLock.efi.
