### ISSUE TITLE
USB Map

### ISSUE THREAD

**Issue by OMandaloriano** [samuel21119/Intel-i9-10900-Gigabyte-Z490-Vision-G-Hackintosh#11]
I remaped the USB using hackintool and discovered the name of the frontal USB-C port and corrected some things, like the 2 USB-A at the front panel and discovered that both internal usb 2.0 are the same because it is a hub.
Pay attention that the USB-C do not have the same name when it is used in USB 2.0
[USB MAP.pdf](https://github.com/samuel21119/Intel-i9-10900-Gigabyte-Z490-Vision-G-Hackintosh/files/5669687/USB.MAP.pdf)

Thank you for the help, it is my firs Hackintosh and you helped me a lot because our system is very similar. How can I talk to you? I have some questions and I am new using GitHub

**Comment by augstb** [comment]
I was coming to open the same issue, I remapped the USB and came to the same conclusions, F_USB1 and F_USB2 are mapped to HS01, it is a hub. Thanks for sharing your research, and thanks @samuel21119 for you preliminary work, was very useful to verify !

**Comment by samuel21119** [comment]
Fixed, thank you for your corporation!
