### ISSUE TITLE
New Bios - CFG Lock

### ISSUE THREAD

**Issue by gandalf027** [samuel21119/Intel-i9-10900-Gigabyte-Z490-Vision-G-Hackintosh#3]
Hey,
A new BIOS is out F6d .. in the D version is supposed to have CFG Lock disabled by default.

Have you tried it?
I have one arriving in a couple of days :).

Thanks for your work.
Rui

**Comment by gandalf027** [comment]
Well, i tried the f6d and it has the CFG option 👍 
Confirmed unlocked with opencore verify msr2.

**Comment by samuel21119** [comment]
I updated to F6 today, it works too.
