### ISSUE TITLE
Ethernet Intel I225-V not working: High Sierra

### ISSUE THREAD

**Issue by vectorseven** [samuel21119/Intel-i9-10900-Gigabyte-Z490-Vision-G-Hackintosh#4]
Hi. I succesfully install High Sierra in a Vision G, using a i5-10400, GTX 1050ti. Overall performance is being great: No crashes, GB5 ok. I had, however, some things to fix since for any reason they are not working "OOB" with your EFI folder a) Ethernet not working, b) Intel HD 630 hardware acceleration not working. I got a thing about this since both problems may be related.

TLDR: I can't see in network system preferences the ethernet option as shown in the image.

![image](https://user-images.githubusercontent.com/66712425/89124978-a701f280-d4a0-11ea-9226-d56fa09ebe6e.png)

What I've tried:

Check PCI path: It seems correct since the MB is the same, anyhow I use Hackintool to be sure

![image](https://user-images.githubusercontent.com/66712425/89125085-7f5f5a00-d4a1-11ea-8c16-ca8018fc0320.png)

![image](https://user-images.githubusercontent.com/66712425/89125090-8e460c80-d4a1-11ea-992e-392354ef5ed6.png)

This is my IORegistry. It seems like I had no appleintel210 just FAKEPCIID.

![image](https://user-images.githubusercontent.com/66712425/89125154-f4329400-d4a1-11ea-986b-f7fa02a57969.png)

But I can't make it work. Any ideas... thanks for your help.

**Comment by rursache** [comment]
give [my EFI](https://github.com/rursache/Hackintosh-i9-10900k-Z490-Vision-G) a try, ethernet is working in Catalina and quick sync as well.

**Comment by samuel21119** [comment]
iMac 19,1 and comet-lake is not officially supported by High Sierra, please install 10.15.5 and check out the dortania's opencore guide.

**Comment by vectorseven** [comment]
> iMac 19,1 and comet-lake is not officially supported by High Sierra, please install 10.15.5 and check out the dortania's opencore guide.

Intel non-macs  aren't officially supported by OSx but here we are.

> give [my EFI](https://github.com/rursache/Hackintosh-i9-10900k-Z490-Vision-G) a try, ethernet is working in Catalina and quick sync as well.

Thanks.

To close this: Main problem is Catalina's IONetworkFamily drivers introduced some changes to support new ethernet Cards, one of them was I255LM (What you all are using through FAKEPCIID), High Sierra lacks this. Thus, no driver can't load since there's no one.
