### ISSUE TITLE
iGPU problem

### ISSUE THREAD

**Issue by goldiiii** [samuel21119/Intel-i9-10900-Gigabyte-Z490-Vision-G-Hackintosh#7]
Hi Samuel,

Thanks a lot! Because of you I got my machine working 👍 

I have the same hardware (without GPU) but I can't solve the iGPU problems. How do I remove the framebuffer patch? (I think I don't have it installed)

I have all the problems you described:

Safari can't open www.fb.com
Firefox quit when opening
VMware Fusion display problem (VM quit when loading vmware tool's display driver)
Can't change account profile picture

**Comment by samuel21119** [comment]
Remove all framebuffer patch, leaving only `AAPL,ig-platform-id: 07009B3E` in your iGPU device properties.
