### ISSUE TITLE
Geekbench score so high

### ISSUE THREAD

**Issue by phao5814** [samuel21119/Intel-i9-10900-Gigabyte-Z490-Vision-G-Hackintosh#8]
I have the same CPU as you but I'm very perplexed as to how you obtained such a high Geekbench CPU score. Are there any other settings in the BIOS that you've enabled that unlocks that extra performance?

My CPU is scoring roughly inline with [benchmarks for the i9 10900 CPU](https://browser.geekbench.com/processors/intel-core-i9-10900) so curious as to how you got your score! Note, I already have Turbo Power Limits disabled on my motherboard.

**Comment by samuel21119** [comment]
I tested on newly installed OS, maybe it's because there's some background process running. I don't think the different score really matters.

**Comment by phao5814** [comment]
Fair enough :) Thought you had some special BIOS settings so thought I'd ask anyways.
